train:
  dataset_path: ../train/data
  train_size: 0.85
  test_size: 0.05
  val_size: 0.1
  batch_size: 32
  epochs: 50
  best_val_loss: 1000
  model_save_path: ./result/model_state.pt
  result_path: ./result/
