train:
  dataset_path: data/train/dataset.csv
  test_size: 0.05
  text_model: 'm3hrdadfi/roberta-zwnj-wnli-mean-tokens'
  image_model: 'openai/clip-vit-base-patch32'
  batch_size: 32
  image_size: 224
  max_len: 80
  clip_config:
    num_hidden_layers: 0
    max_position_embeddings: 0
    vocab_size: 0
    hidden_size: 1
    patch_size: 1
